name: adorsho_nibash_app
description: "আদর্শ নিবাস (মজুমদার) - Rent Management App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  flutter_riverpod: ^2.6.1
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.2
  google_fonts: ^6.2.1
  intl: ^0.20.2
  flutter_html_to_pdf:
    path: third_party/flutter_html_to_pdf
  share_plus: ^13.1.0
  path_provider: ^2.1.5
  excel: ^4.0.6
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
  fonts:
    - family: NotoSansBengali
      fonts:
        - asset: assets/fonts/NotoSansBengali-Regular.ttf
        - asset: assets/fonts/NotoSansBengali-Bold.ttf
          weight: 700
